'use client';

import React, { useRef, useState, useCallback } from 'react';
import * as htmlToImage from 'html-to-image';
import { jsPDF } from 'jspdf';

interface ReportCardProps {
  summary: string;
  category: 'tw_trends' | 'us_stocks';
  date: string;
  lineSent?: boolean;
}

const ReportCard: React.FC<ReportCardProps> = ({ summary, category, date, lineSent }) => {
  const cardRef = useRef<HTMLDivElement>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const title = category === 'tw_trends' ? '🇹🇼 台股即時晨報' : '🇺🇸 美股即時快訊';
  const gradientClass = category === 'tw_trends' 
    ? 'from-indigo-600 to-violet-600' 
    : 'from-emerald-600 to-teal-600';
  const fileName = `${category}_${date.replace(/\//g, '-')}.pdf`;

  const handleDownload = useCallback(async () => {
    if (!cardRef.current) return;
    
    setIsGenerating(true);
    try {
      const element = cardRef.current;
      
      // 使用 html-to-image 將 DOM 轉為 PNG Data URL
      const dataUrl = await htmlToImage.toPng(element, {
        quality: 1,
        pixelRatio: 2,
        backgroundColor: '#ffffff', // 強制白底輸出
        style: {
          transform: 'scale(1)',
          transition: 'none',
          color: '#000000', // 強制黑色字體
        }
      });

      // 取得圖片寬高以維持比例
      const img = new Image();
      img.src = dataUrl;
      await new Promise((resolve) => (img.onload = resolve));

      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'px',
        format: [img.width / 2, img.height / 2]
      });

      pdf.addImage(dataUrl, 'PNG', 0, 0, img.width / 2, img.height / 2);
      pdf.save(fileName);
    } catch (error: any) {
      console.error('PDF generation error detail:', error);
      alert(`PDF 生成失敗: ${error.message || '庫解析錯誤'}。建議直接對螢幕進行截圖分享。`);
    } finally {
      setIsGenerating(false);
    }
  }, [fileName]);

  return (
    <div className="space-y-4">
      {/* 這是被擷取區域 */}
      <article 
        ref={cardRef}
        className="rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm dark:border-zinc-800 dark:bg-zinc-900 overflow-hidden"
      >
        <div className="mb-4 flex flex-col gap-1 border-b border-zinc-100 pb-3 dark:border-zinc-800 text-left">
          <h2 className={`text-xl font-black bg-clip-text text-transparent bg-gradient-to-r ${gradientClass} tracking-tight`}>
            {title}
          </h2>
          <div className="flex justify-between items-center text-[9px] font-bold text-zinc-400 uppercase tracking-widest">
            <span>{category.replace('_', ' ')}</span>
            <span>{date}</span>
          </div>
        </div>

        <div className="prose prose-zinc dark:prose-invert max-w-none text-left">
          <pre className="whitespace-pre-wrap font-sans text-[13px] leading-relaxed text-zinc-900 dark:text-zinc-100">
            {summary}
          </pre>
        </div>

        <div className="mt-6 flex items-center justify-between border-t border-zinc-50 pt-3 dark:border-zinc-800/50">
          <div className="flex gap-2">
            {lineSent && (
              <span className="inline-flex items-center rounded-full bg-blue-100 px-2 py-0.5 text-[9px] font-bold text-blue-800 dark:bg-blue-900/30 dark:text-blue-400">
                SENT TO LINE
              </span>
            )}
          </div>
          <span className="text-[9px] text-zinc-300 italic">Generated by Global Investment Assistant</span>
        </div>
      </article>

      {/* 下載按鈕 */}
      <button
        onClick={handleDownload}
        disabled={isGenerating}
        className="flex w-full items-center justify-center gap-2 rounded-xl border border-zinc-200 bg-white px-4 py-3 text-sm font-bold text-zinc-700 shadow-sm transition-all hover:bg-zinc-50 active:scale-[0.98] disabled:opacity-50 dark:border-zinc-800 dark:bg-zinc-900/50 dark:text-zinc-300 dark:hover:bg-zinc-800"
      >
        {isGenerating ? (
          <>
            <div className="h-4 w-4 animate-spin rounded-full border-2 border-zinc-300 border-t-zinc-600" />
            正在生成 PDF...
          </>
        ) : (
          <>
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v4" />
              <polyline points="7 10 12 15 17 10" />
              <line x1="12" y1="15" x2="12" y2="3" />
            </svg>
            💾 下載 PDF 報表
          </>
        )}
      </button>
    </div>
  );
};

export default ReportCard;
