'use client';

import React, { useRef, useState } from 'react';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

interface ReportCardProps {
  summary: string;
  category: 'tw_trends' | 'us_stocks';
  date: string;
  lineSent?: boolean;
}

const ReportCard: React.FC<ReportCardProps> = ({ summary, category, date, lineSent }) => {
  const cardRef = useRef<HTMLDivElement>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const title = category === 'tw_trends' ? '🇹🇼 台股即時晨報' : '🇺🇸 美股即時快訊';
  const gradientClass = category === 'tw_trends' 
    ? 'from-indigo-600 to-violet-600' 
    : 'from-emerald-600 to-teal-600';
  const fileName = `${category}_${date.replace(/\//g, '-')}.pdf`;

  const handleDownload = async () => {
    if (!cardRef.current) return;
    
    setIsGenerating(true);
    try {
      // 擷取前暫時短暫調整樣式優化圖片品質
      const element = cardRef.current;
      
      const canvas = await html2canvas(element, {
        scale: 2, // 提高解析度
        useCORS: true,
        backgroundColor: '#ffffff',
        logging: false,
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'px',
        format: [canvas.width / 2, canvas.height / 2] // 保持比例
      });

      pdf.addImage(imgData, 'PNG', 0, 0, canvas.width / 2, canvas.height / 2);
      pdf.save(fileName);
    } catch (error) {
      console.error('PDF generation failed:', error);
      alert('PDF 生成失敗，請再試一次。');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-4">
      {/* 這是會被擷取成 PDF 的區域 */}
      <article 
        ref={cardRef}
        className="rounded-2xl border border-zinc-200 bg-white p-8 shadow-sm dark:border-zinc-800 dark:bg-zinc-900"
      >
        <div className="mb-6 flex flex-col gap-2 border-b border-zinc-100 pb-4 dark:border-zinc-800">
          <h2 className={`text-2xl font-black bg-clip-text text-transparent bg-gradient-to-r ${gradientClass} tracking-tight`}>
            {title}
          </h2>
          <div className="flex justify-between items-center">
            <span className="text-xs font-bold text-zinc-400 uppercase tracking-widest">{category}</span>
            <span className="text-xs font-medium text-zinc-500">{date}</span>
          </div>
        </div>

        <div className="prose prose-zinc dark:prose-invert max-w-none">
          <pre className="whitespace-pre-wrap font-sans text-base leading-relaxed text-zinc-800 dark:text-zinc-200">
            {summary}
          </pre>
        </div>

        <div className="mt-8 flex items-center justify-between border-t border-zinc-50 pt-4 dark:border-zinc-800/50">
          <div className="flex gap-2">
            {lineSent && (
              <span className="inline-flex items-center rounded-full bg-blue-100 px-2 py-0.5 text-[10px] font-bold text-blue-800 dark:bg-blue-900/30 dark:text-blue-400">
                SENT TO LINE
              </span>
            )}
          </div>
          <span className="text-[10px] text-zinc-300 italic">Generated by Global Investment Assistant</span>
        </div>
      </article>

      {/* 下載按鈕 (不包含在擷取區域內) */}
      <button
        onClick={handleDownload}
        disabled={isGenerating}
        className="flex w-full items-center justify-center gap-2 rounded-xl border border-zinc-200 bg-white px-4 py-3 text-sm font-bold text-zinc-700 shadow-sm transition-all hover:bg-zinc-50 active:scale-[0.98] disabled:opacity-50 dark:border-zinc-800 dark:bg-zinc-900/50 dark:text-zinc-300 dark:hover:bg-zinc-800"
      >
        {isGenerating ? (
          <>
            <div className="h-4 w-4 animate-spin rounded-full border-2 border-zinc-300 border-t-zinc-600" />
            正在生成 PDF...
          </>
        ) : (
          <>
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v4" />
              <polyline points="7 10 12 15 17 10" />
              <line x1="12" y1="15" x2="12" y2="3" />
            </svg>
            💾 下載報表 PDF (分享專用)
          </>
        )}
      </button>
    </div>
  );
};

export default ReportCard;
